### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by leftforlol** [BLCM/BLCMods#1064] opened 2018-07-19 17:41 UTC
When I first tried to open the mod manager after downloading it said I needed to update Java, which I did. However after I updated Java I still couldn't open and it would give me the error Java Virtual Machine Launcher "A java exception has occurred ". I've tried to reinstall the BLCMM, but that didn't help at all. Any help would be greatly appreciated.

**Comment by nicmr** [comment] 2018-07-19 18:33
Duplicate of #1063

**Comment by olga193580** [comment] 2018-07-21 08:49
# 1064

**Comment by LightChaosman** [comment] 2018-07-21 11:06
Has been fixed, redownload the launcher if it still occurs

**Closed by LightChaosman** 2018-07-21 11:06 UTC
